# GitHub Sponsors configuration for Neovim Ultimate Edition

# Uncomment and add your sponsor links when ready
# github: [quadbyte]
# patreon: your_patreon
# open_collective: your_opencollective
# ko_fi: your_kofi
# custom: ["https://your-sponsor-link.com"]

# Note: Remove this file if not using GitHub Sponsors
# To enable sponsorship, uncomment the relevant lines above and add your sponsor information
